- name: Set BBR
  ansible.posix.sysctl:
    name: net.core.default_qdisc
    value: "fq"
    state: present
- name: Set queue
  ansible.posix.sysctl:
    name: net.ipv4.tcp_congestion_control
    value: "bbr"
    state: present